function [x, y] = ff_points_random(theta1, theta2, n)
% generated by AI
% Generates n random points on the unit circle between two angles
%
% Inputs:
%   theta1, theta2 : start and end angles in radians
%   n              : number of points
%
% Outputs:
%   x, y : 1 x n arrays of coordinates on the unit circle

    % Random angles between theta1 and theta2
    angles = theta1 + (theta2 - theta1) * rand(1, n);

    % Unit circle coordinates
    x = cos(angles);
    y = sin(angles);
end