function [x, y] = ff_points_equally_spaced(theta1, theta2, n)
% generated by AI
% Generates n points on the unit circle between two angles
%
% Inputs:
%   theta1, theta2 : start and end angles in radians
%   n              : number of points
%
% Outputs:
%   x, y : 1 x n arrays of coordinates on the unit circle

    % Linearly spaced angles
    angles = linspace(theta1, theta2, n);

    % Unit circle coordinates
    x = cos(angles);
    y = sin(angles);
end