function [vals, x, y] = scat_field_data(lp, curve, density, xlims, ylims, k, ppwl)
% generated by AI
% SCAT_FIELD_DATA
% Generate and plot scattered field data on a Cartesian grid.
%
% Inputs:
%   lp    
%   density : The layer potential object
%   xlims - [xmin xmax]
%   ylims - [ymin ymax]
%   k     - wavenumber
%   ppwl  - points per wavelength
%
% Output:
%   vals: The scattered field values
%   x,y : The x and y values of the grid

    % Wavelength and grid spacing
    lambda = 2*pi / real(k);
    h = lambda / ppwl;

    % Grid vectors
    x = xlims(1):h:xlims(2);
    y = ylims(1):h:ylims(2);

    vals = zeros(length(x), length(x));

  
    ny = length(y);
    parfor xind = 1:length(x)
        for yind = 1:ny
            if curve.test_distance(x(xind), y(yind))
                vals(xind, yind) = lp.sol_rep_mat(k, [x(xind); y(yind)]) * density;
            end
        end
    end

    % Plot
    % figure;
    % imagesc(x, y, real(U));
    % axis equal tight;
    % set(gca, 'YDir', 'normal');
    % colorbar;
    % title('Real part of scattered field');
    % xlabel('x');
    % ylabel('y');
end